name: 'Activate Namespace'
description: 'Activate a namespace and get the credentials for a Okteto Cloud namespace'
inputs: 
  namespace:
    description: 'The target Kubernetes namespace.'
    required: false
    default: ''
  log-level:
    description: "Log level string. Valid options are debug, info, warn, error"
    required: false 
outputs:
  kubeconfig: 
    description: 'The path to the kubeconfig'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.namespace }}
    - ${{ inputs.log-level }}
branding:
  icon: 'arrow-up-circle'  
  color: 'green'